name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Install dependencies
      run: |
        sudo apt update && \
        sudo apt install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev \
          libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config ffmpeg wget && \
        wget "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux" && \
        sudo mv yt-dlp_linux /usr/bin/yt-dlp

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
